### ISSUE TITLE
Where could I access the traces in your experiment

### ISSUE THREAD

**Issue by wen-zheng** [venkatarun95/CopaEvaluation#1]
Hi, I want to reproduce your results, but I can't access the traces in your experiment. Where could I access the traces in your experiment or how to create them by myself?

**Comment by venkatarun95** [comment]
You can find the cellular network traces at: https://github.com/ravinet/mahimahi/tree/master/traces. Let me know if this is what you were looking for

**Comment by wen-zheng** [comment]
Thanks, except cellular traces, are all the traces "trace-32Mbps, trace-12Mbps, trace-42Mbps" constant?

**Comment by venkatarun95** [comment]
Yes

**Comment by wen-zheng** [comment]
Thanks
