### ISSUE TITLE
About experiment-tcp-compatibility.sh

### ISSUE THREAD

**Issue by wen-zheng** [venkatarun95/CopaEvaluation#2]
Hi, can you provide the raw results of this script to me? I want to use them to plot something like the bandwidth stolen ratio. can you help me?

**Comment by venkatarun95** [comment]
I don't have the raw results with me. Running the script should produce the results you want. Are you having issues?

**Comment by wen-zheng** [comment]
Is running the command like "bash experiment-tcp-compatibility.sh" enough?

**Comment by venkatarun95** [comment]
I think so. The dependencies are `tcpdump tcptrace python3 mahimahi`. You can get `mahimahi` at http://mahimahi.mit.edu/

**Comment by wen-zheng** [comment]
Thanks.
